export const data = {
        "nodes": [
            {"id": "1", "yes": "2", "no": "16", "value": "¿Has tenido fiebre?", "isLeaf":false},
            {"id": "2", "yes": "3", "no": "", "value": "¿Tienes manchas en tu cuerpo?", "isLeaf":false},
            {"id": "3", "yes": "4", "no": "10", "value": "¿Tienes llagas en los genitales?", "isLeaf":false},
            {"id": "4", "yes": "5", "no": "", "value": "¿Presentas algún síntoma anterior pero sin dolor?", "isLeaf":false},
            {"id": "5", "yes": "6", "no": "", "value": "¿Has tenido sudoración en las manos y en los pies?", "isLeaf":false},
            {"id": "6", "yes": "7", "no": "", "value": "¿Has tenido dolor de garganta?", "isLeaf":false},
            {"id": "7", "yes": "8", "no": "", "value": "¿Tienes úlcercas?", "isLeaf":false},
            {"id": "8", "yes": "9", "no": "", "value": "¿Te ha sangrao la boca?", "isLeaf":false},
            {"id": "9", "yes": null, "no": null, "value": "Sifilis", "isLeaf":true},
            {"id": "10", "yes": "11", "no": "", "value": "¿Sientes dolor abdominal?", "isLeaf":false},
            {"id": "11", "yes": "12", "no": "22", "value": "¿Has tenido dolor de cabeza con mayor frecuencia?", "isLeaf":false},
            {"id": "12", "yes": "13", "no": "", "value": "¿Has tenido naúsea o vómito?", "isLeaf":false},
            {"id": "13", "yes": "14", "no": "", "value": "¿Has tenido más cansancio de lo normal?", "isLeaf":false},
            {"id": "14", "yes": "15", "no": "", "value": "¿Has sentido menos apetito?", "isLeaf":false},
            {"id": "15", "yes": null, "no": null, "value": "hepatitis", "isLeaf":true},
            {"id": "16", "yes": "17", "no": "", "value": "¿Has tenido diarrea?", "isLeaf":false},
            {"id": "17", "yes": "18", "no": "", "value": "¿Has tenido fluido lechoso?", "isLeaf":false},
            {"id": "18", "yes": "19", "no": "", "value": "¿Has tenido ganas de orinar con mayor frecuencia?", "isLeaf":false},
            {"id": "19", "yes": "20", "no": "", "value": "¿Sientes dolor al orinar?", "isLeaf":false},
            {"id": "20", "yes": "21", "no": "23", "value": "¿Tienes sangrado en entre periodos menstruales?", "isLeaf":false},
            {"id": "21", "yes": null, "no": null, "value": "gonorrea", "isLeaf":true},
            {"id": "22", "yes": "20", "no": "", "value": "¿Sientes dolor al tener sexo?", "isLeaf":false},
            {"id": "23", "yes": "24", "no": "", "value": "¿Has sentido inflamación o ardor en los testículos?", "isLeaf":false},
            {"id": "24", "yes": null, "no": null, "value": "clamidia", "isLeaf":true},
        ],
            "root": "1"
}
